	<section>
				<div id="contieneformulario">
					<h3>Formulario de contacto</h3>
					<p>Se desea ponerse en contacto conmigo, rellene este formulario:</p>
					<form method="POST" action="procesaformulario.php">
						<div class="formleyenda">Nombre:</div>
						<input type="text" name="nombre" id="nombre">
						<div class="formleyenda">Correo electrónico</div>
						<input type="text" name="email" id="email">
						<div class="formleyenda">Mensaje</div>
						<textarea name="mensaje"></textarea>
						<input type="submit" value="Enviar" id="botonenviar"> 
					</form>
				</div>
			</section>
			<div style="clear:both"></div>
