<section>
				<div id="contieneportafolio">
				<article class="artportafolio" id="porta1">
					<div class="contieneportafoliointerior">
						<h3>Título del proyecto</h3>
						<p>Breve descripción</p>
						<div class="imagenportafolio" id="portafolio1"></div>
					</div>
				</article>
			
				<article class="artportafolio" id="porta1">
					<div class="contieneportafoliointerior">
						<h3>Título del proyecto</h3>
						<p>Breve descripción</p>
						<div class="imagenportafolio" id="portafolio2"></div>
					</div>
				</article>
				<article class="artportafolio" id="porta1">
					<div class="contieneportafoliointerior">
						<h3>Título del proyecto</h3>
						<p>Breve descripción</p>
						<div class="imagenportafolio" id="portafolio3"></div>
					</div>
				</article>
				<article class="artportafolio" id="porta1">
					<div class="contieneportafoliointerior">
						<h3>Título del proyecto</h3>
						<p>Breve descripción</p>
						<div class="imagenportafolio" id="portafolio4"></div>
					</div>
				</article>
				<article class="artportafolio" id="porta1">
					<div class="contieneportafoliointerior">
						<h3>Título del proyecto</h3>
						<p>Breve descripción</p>
						<div class="imagenportafolio" id="portafolio5"></div>
					</div>
				</article>
				<article class="artportafolio" id="porta1">
					<div class="contieneportafoliointerior">
						<h3>Título del proyecto</h3>
						<p>Breve descripción</p>
						<div class="imagenportafolio" id="portafolio6"></div>
					</div>
				</article>
				<article class="artportafolio" id="porta1">
					<div class="contieneportafoliointerior">
						<h3>Título del proyecto</h3>
						<p>Breve descripción</p>
						<div class="imagenportafolio" id="portafolio7"></div>
					</div>
				</article>
				<article class="artportafolio" id="porta1">
					<div class="contieneportafoliointerior">
						<h3>Título del proyecto</h3>
						<p>Breve descripción</p>
						<div class="imagenportafolio" id="portafolio8"></div>
					</div>
				</article>
				<div style="clear:both;"></div>
				</div>
				
			</section>
